### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by u7327620** [u7327620/zt_rename_to_feature_added#1]
Whilst the visuals are as intended, the tests are failing and need to be updated... 

Additionally, I'll send a message regarding the progress into the development chat as soon as I can fix the application...

**Comment by u7332137** [comment]
There could possibly be an issue that it is returning headers on mentioned or starred type of streams which could be causing the length of the views to be consistently one-too-large?

**Comment by u7327620** [comment]
Did some testing and found that it's not excluding topic-narrow streams for the header messages so I'll have to re-assess what's going on with the <stream> vs <stream, topic>.

Side Note: fixed the terminal issue I was having after a few hours. I think if you're on a certain view stage in the web-app that the terminal hasn't implemented yet, the terminal will crash with an "out_of_focus" index error... Could maybe follow this up with a report on the main repo.

**Comment by tawhidlabib** [comment]
Hey,
After inspecting this issue, I believe that he was trying bring up the problem within searches which always have the same recipients (i.e. topic narrows and dms). We need to change it so that the status and date are displayed.

**Comment by u7327620** [comment]
Update: Through testing via sending myself dms, the tests were failing because enabling recipient headers within a message with yourself obliterates their existence?!

**Comment by u7327620** [comment]
Amended the commit with updated logic that restricts to only the requested search cases. Next step would be the status bar on every message...
